export default eventHandler(async (event) => {
  const services = [
    {
      uuid: '74cd01c7-c8ad-4b04-a1a2-37c4fa2a57d6',
      name: 'Rutube',
      items: [
        'ИИ продвижение',
        'Запуск рекламы',
        'Подписки на аккаунт',
        'Курсы',
        'Продвижение',
      ],
      mainImage: '/img/catalog/rutube.png',
      images: [],
      video: 'null',
      price: 20,
      rating: 0,
      advanced: 0,
      slug: 'rutube',
      description: '',
    },
    {
      uuid: '12b049c0-3b19-4593-8239-502c7cde72dd',
      name: 'Yappy',
      items: [
        'ИИ продвижение',
        'Запуск рекламы',
        'Подписки на аккаунт',
        'Курсы',
        'Продвижение',
      ],
      mainImage: '/img/catalog/yappy.png',
      images: [],
      video: 'null',
      price: 20,
      rating: 0,
      advanced: 0,
      slug: 'yappy',
      description: '',
    },
    {
      uuid: '74cd01c7-c8ad-4b04-a1a2-37c4fa2a57d6',
      name: 'Rutube',
      items: [
        'ИИ продвижение',
        'Запуск рекламы',
        'Подписки на аккаунт',
        'Курсы',
        'Продвижение',
      ],
      mainImage: '/img/catalog/rutube.png',
      images: [],
      video: 'null',
      price: 20,
      rating: 0,
      advanced: 0,
      slug: 'rutube',
      description: '',
    },
    {
      uuid: '439e01ea-6124-4aa1-9dac-06da052d6849',
      name: 'Instagram',
      items: [
        'ИИ продвижение',
        'Запуск рекламы',
        'Подписки на аккаунт',
        'Курсы',
        'Продвижение',
      ],
      mainImage: '/img/catalog/instagram.png',
      images: [],
      video: 'null',
      price: 20,
      rating: 0,
      advanced: 0,
      slug: 'instagram',
      description: '',
    },
    {
      description: '',
      uuid: '0db9409b-4107-45bb-9c61-2d606dcbc717',
      name: 'Facebook',
      items: [
        'ИИ продвижение',
        'Запуск рекламы',
        'Подписки на аккаунт',
        'Курсы',
        'Продвижение',
      ],
      mainImage: '/img/catalog/facebook.png',
      images: [],
      video: 'null',
      price: 20,
      rating: 0,
      advanced: 0,
      desctiption: '',
      slug: 'facebook',
    },
    {
      uuid: '9bc33d0c-ad91-4426-ac31-135106bea05a',
      name: 'YouTube',
      items: [
        'ИИ продвижение',
        'Запуск рекламы',
        'Подписки на аккаунт',
        'Курсы',
        'Продвижение',
      ],
      mainImage: '/img/catalog/youtube.png',
      images: [],
      video: 'null',
      price: 20,
      rating: 0,
      advanced: 0,
      slug: 'youtube',
      description: '',
    },
    {
      uuid: '75d82395-c4ab-4b04-a322-d790b5829f48',
      name: 'Pinterest',
      items: [
        'ИИ продвижение',
        'Запуск рекламы',
        'Подписки на аккаунт',
        'Курсы',
        'Продвижение',
      ],
      mainImage: '/img/catalog/pinterest.png',
      images: [],
      video: 'null',
      price: 20,
      rating: 0,
      advanced: 0,
      slug: 'pinterest',
      description: '',
    },
  ]

  if (!services || !services.length) {
    return {
      status: 'error',
      error: [],
    }
  }

  return {
    status: 'ok',
    services,
  }
})
