import { getServerSession } from '#auth'
import request from 'request'
const config = useRuntimeConfig()
const proxy = config.CHANGING_PROXY
const elPerPage = 50
const apiKey = config.serverLoadApiKey

export default eventHandler(async (event) => {
  const session = (await getServerSession(event)) as any
  if (!session) return sendRedirect(event, '/auth', 302)

  const { article, limit, page } = getQuery(event)

  if (!article) {
    return send(event, {
      status: 400,
      body: 'Article is required',
    })
  }

  // const data: any = await $fetch('http://95.163.249.133:4141', {
  //   method: 'POST',
  //   parseResponse: JSON.parse,
  //   body: {
  //     type: 'ozonReviews',
  //     url: `https://www.ozon.ru/product/${article}/`,
  //     count: elPerPage,
  //   },
  // })

  const data = [
    {
      id: '018ed2e3-6f29-d490-f3f7-3cb07a506b36',
      rating: 5,
      text: 'пушка',
      productArticle: 1301187703,
      positiveText: 'очень приятный звук на гифт свитчах',
      negativeText: '-',
      user: {
        name: 'Пользователь предпочёл скрыть свои данные',
        country: 'Россия',
      },
      likes: 0,
      dislikes: 0,
      comments: [],
      rank: 1,
    },
    {
      id: '018ed167-ced1-4170-7bb6-f88bee8f3ac7',
      rating: 5,
      text: 'стоит тонн',
      productArticle: 1300950270,
      positiveText: '',
      negativeText: '',
      user: {
        name: 'Иван П.',
        country: 'Россия',
      },
      likes: 0,
      dislikes: 0,
      comments: [],
      rank: 2,
    },
    {
      id: '018ed297-ef43-46e5-d9e7-489bba87ed8b',
      rating: 5,
      text: 'Клавиатура кайфовая,  подсветка полностью регулируется через софт,  можно поставить абсолютно любой цвет. \nДостаточно тихая,  пользуюсь около месяца,  проблем не обнаружил.',
      productArticle: 1210358865,
      positiveText: '',
      negativeText: '',
      user: {
        name: 'Дмитрий У.',
        country: 'Россия',
      },
      likes: 0,
      dislikes: 0,
      comments: [
        {
          id: '018ed2a3-2434-b9c2-6a71-f9207e1b12f3',
          text: 'Где скачали софт? Можете написать сайт, пожалуйста',
          user: {
            name: 'h g.',
            country: 'Россия',
          },
          likes: 0,
          dislikes: 0,
          rank: 1,
        },
        {
          id: '018ed301-7e56-a260-5b45-3499bc41fe63',
          text: 'На сайте ajazz по',
          user: {
            name: 'Роман Ф.',
            country: 'Россия',
          },
          likes: 0,
          dislikes: 0,
          rank: 2,
        },
      ],
      rank: 3,
    },
    {
      id: '018ecf6a-ed3a-eb05-04ab-1c867ffc3ca1',
      rating: 5,
      text: 'Супер!',
      productArticle: 1210358981,
      positiveText: '',
      negativeText: '',
      user: {
        name: 'Пользователь предпочёл скрыть свои данные',
        country: 'Россия',
      },
      likes: 0,
      dislikes: 0,
      comments: [],
      rank: 4,
    },
    {
      id: '018ece42-74fe-4016-85e3-3c6f1cb55aec',
      rating: 5,
      text: 'Отлично',
      productArticle: 1301183190,
      positiveText: 'Отлично',
      negativeText: 'Отлично',
      user: {
        name: 'Камиль Э.',
        country: 'Россия',
      },
      likes: 0,
      dislikes: 0,
      comments: [],
      rank: 5,
    },
    {
      id: '018ecd16-fc15-64db-2001-7b5eb0ad32e4',
      rating: 5,
      text: 'Шикарно. Пальцы летают и абсолютно не устают. Стабилизаторы отрабатывают и пробел с шифтами не перекашивает.\nЕдинственный косяк (к самой клаве отношения не имеющий) - не положили в комплект пластиковую крышку от пыли, которая заявлена в нём',
      productArticle: 1210359103,
      positiveText: '',
      negativeText: '',
      user: {
        name: 'Ярослав М.',
        country: 'Россия',
      },
      likes: 0,
      dislikes: 0,
      comments: [],
      rank: 6,
    },
    {
      id: '018ec422-ee2b-33f0-c005-3c7a9710d852',
      rating: 5,
      text: 'Плюсы- качество сборки, заявленные характеристики, тихий тайпинг(очень тихий)\nМинусы- доставка 3-4 недели,не понятно как настраивать экран.',
      productArticle: 1300950270,
      positiveText: '',
      negativeText: '',
      user: {
        name: 'Андрей Х.',
        country: 'Россия',
      },
      likes: 0,
      dislikes: 0,
      comments: [],
      rank: 7,
    },
    {
      id: '018ec770-de27-509c-994f-e21d643c0903',
      rating: 5,
      text: 'клавиатура хорошая за свою цену, только жаль, что нет русской раскладки',
      productArticle: 1210359103,
      positiveText: '',
      negativeText: '',
      user: {
        name: 'Валерия Ш.',
        country: 'Россия',
      },
      likes: 0,
      dislikes: 0,
      comments: [
        {
          id: '018ec82a-8d96-6d41-6581-18fea5b764b5',
          text: 'от этого продавца же есть клавиатуры с русской раскладкой',
          user: {
            name: 'Эдуард Р.',
            country: 'Россия',
          },
          likes: 0,
          dislikes: 0,
          rank: 1,
        },
      ],
      rank: 8,
    },
    {
      id: '018ec758-423c-1d80-c365-405606643994',
      rating: 5,
      text: 'Лучшая клавиатура которая у меня была. Хороший крим звук',
      productArticle: 1210357482,
      positiveText: '',
      negativeText: '',
      user: {
        name: 'Николай П.',
        country: 'Россия',
      },
      likes: 0,
      dislikes: 0,
      comments: [
        {
          id: '018ec7d3-099a-70cf-fd98-6ef65ebe03f8',
          text: 'а откуда русские буквы?Это наклейка?',
          user: {
            name: 'Ирма Д.',
            country: 'Россия',
          },
          likes: 0,
          dislikes: 0,
          rank: 1,
        },
      ],
      rank: 9,
    },
    {
      id: '018ec131-0aa8-c5d5-c050-bce95092ac09',
      rating: 5,
      text: 'Брал за 2800 с учетом бонусов. Пришла за 20 дней в Ростовскую область. За свои деньги очень хорошая клавиатура, тихая (на всех видео звучит хуже, чем в жизни), приятный тайпинг, смазаные свичи и стабы. Главное не берите чисто белую/черную и бело-серую версии, в них хуже свичи и кейкапы.',
      productArticle: 1210358865,
      positiveText: '',
      negativeText: '',
      user: {
        name: 'Роман Б.',
        country: 'Россия',
      },
      likes: 0,
      dislikes: 0,
      comments: [],
      rank: 10,
    },
    {
      id: '018ebe84-36dd-4a1f-1bc2-19d7e22f33f4',
      rating: 5,
      text: '',
      productArticle: 1210358865,
      positiveText: '',
      negativeText: '',
      user: {
        name: 'Данис Ч.',
        country: 'Россия',
      },
      likes: 0,
      dislikes: 0,
      comments: [],
      rank: 11,
    },
    {
      id: '018ebe82-dfce-36ad-b14c-90ea6bcacf82',
      rating: 5,
      text: 'Клавиатуру брал за 2700. Могут быть непривычны очень мягкие нажатия на клавиши.',
      productArticle: 1210358742,
      positiveText:
        'Отличная клавиатура за такие деньги, приятный звук нажатий и отличное качество сборки, 18 режимов подсветки',
      negativeText: 'Действительно придраться не к чему',
      user: {
        name: 'Егор Г.',
        country: 'Россия',
      },
      likes: 0,
      dislikes: 0,
      comments: [],
      rank: 12,
    },
    {
      id: '018ebe0b-9fe9-5a19-18d8-12a4dde954af',
      rating: 5,
      text: 'звук просто прекрасный, формфактор для меня лично удобнейший из всех, дизайн тоже отличный, роллер для регулировки громкости, нормальный посредственный софт, пользоваться им можно',
      productArticle: 1210357482,
      positiveText: 'все',
      negativeText: 'ничего',
      user: {
        name: 'Arslan B.',
        country: 'Россия',
      },
      likes: 0,
      dislikes: 0,
      comments: [],
      rank: 13,
    },
    {
      id: '018ebde0-b3df-3e0d-e60c-f4a9ab59d7fd',
      rating: 5,
      text: '',
      productArticle: 1210359333,
      positiveText: '',
      negativeText: '',
      user: {
        name: 'Пользователь предпочёл скрыть свои данные',
        country: 'Россия',
      },
      likes: 0,
      dislikes: 0,
      comments: [],
      rank: 14,
    },
    {
      id: '018ebcac-1887-0541-6755-f4c873976803',
      rating: 5,
      text: 'Клавиатура в идеальном состояние ,пришла как по описаниб',
      productArticle: 1300950270,
      positiveText: '',
      negativeText: '',
      user: {
        name: 'Пользователь предпочёл скрыть свои данные',
        country: 'Россия',
      },
      likes: 0,
      dislikes: 0,
      comments: [],
      rank: 15,
    },
    {
      id: '018ebc73-78ee-161e-600d-8a4cb496d5d4',
      rating: 4,
      text: 'Отличная клавиатура, хорошая цена, единственный минус так это отсутствие русскоязычной раскладки на клавиатуре.',
      productArticle: 1300950270,
      positiveText: '',
      negativeText: '',
      user: {
        name: 'Александр Р.',
        country: 'Россия',
      },
      likes: 0,
      dislikes: 0,
      comments: [],
      rank: 16,
    },
    {
      id: '018eba71-3363-000d-2326-7c367b47977b',
      rating: 5,
      text: 'Первая механика ,не с чем сравнить.',
      productArticle: 1210358742,
      positiveText: 'Работает',
      negativeText: 'Пока не обнаружил',
      user: {
        name: 'Ольга Ч.',
        country: 'Россия',
      },
      likes: 0,
      dislikes: 0,
      comments: [],
      rank: 17,
    },
    {
      id: '018eb88c-cd3d-7662-2f41-bb10fece5311',
      rating: 5,
      text: 'Все пришло довольно быстро, все целое и работает это уже не может не устраивать 🤩',
      productArticle: 1210358865,
      positiveText: '',
      negativeText: '',
      user: {
        name: 'Пользователь предпочёл скрыть свои данные',
        country: 'Россия',
      },
      likes: 0,
      dislikes: 0,
      comments: [],
      rank: 18,
    },
    {
      id: '018eb85f-cb79-78d9-d841-be8094bdc659',
      rating: 5,
      text: 'Топ за свои бабки,меняете свитчи на тихие и клава просто бомба за свои деньги',
      productArticle: 1210358981,
      positiveText: '',
      negativeText: '',
      user: {
        name: 'Антон Б.',
        country: 'Россия',
      },
      likes: 0,
      dislikes: 0,
      comments: [],
      rank: 19,
    },
    {
      id: '018eb850-36e3-ddc0-1ea1-e41ed862401a',
      rating: 1,
      text: 'приехал брак. не работает пробел, плохо прожимается кнопка M, помятая коробка\nжалею что потратил свое время на это, куплю другую клаву',
      productArticle: 1300950270,
      positiveText: '',
      negativeText: '',
      user: {
        name: 'Шамсиддинов Ш.',
        country: 'Россия',
      },
      likes: 0,
      dislikes: 3,
      comments: [],
      rank: 20,
    },
    {
      id: '018eb49d-4d7c-8e2b-6d14-7fbcd4aebc77',
      rating: 5,
      text: 'За свои деньги топ, тяжелая, куча шумки, смазана, взял черную там нет экрана, и подсветка только белая. Строго, но прикольно. Можно еще оринги под кепки надеть и будет супер, подключение только по проводу',
      productArticle: 1210358742,
      positiveText: '',
      negativeText: '',
      user: {
        name: 'Алексей И.',
        country: 'Россия',
      },
      likes: 0,
      dislikes: 0,
      comments: [],
      rank: 21,
    },
    {
      id: '018eb405-fd49-0799-4334-6c8ba2e7d986',
      rating: 5,
      text: 'Бомба за свои деньги',
      productArticle: 1210357482,
      positiveText: '',
      negativeText: '',
      user: {
        name: 'Наталья М.',
        country: 'Россия',
      },
      likes: 0,
      dislikes: 0,
      comments: [],
      rank: 22,
    },
    {
      id: '018eb2e3-854a-e726-7dbd-2f2890fd2b9b',
      rating: 5,
      text: 'Одна из лучших клавиатур в своем сегменте! Свитчи линейные, тихие. Табы смазаны. Экранчик работает, но есть нюанс он не работает на 2.4 принципе потеря не большая.',
      productArticle: 1300950270,
      positiveText: '',
      negativeText: '',
      user: {
        name: 'Наталья М.',
        country: 'Россия',
      },
      likes: 0,
      dislikes: 0,
      comments: [],
      rank: 23,
    },
    {
      id: '018eb28b-8495-7c1e-71e4-ef00b9832701',
      rating: 4,
      text: 'можно брать, скачайте программу с a-jazz и поиграйтесь настройками подсветки',
      productArticle: 1210358742,
      positiveText: 'цена за механику, работает',
      negativeText:
        '1) эргономика - после предыдущей клавы лоджитеч k520 - к этой приходится приноровиться; 2) как будто трещины на пластике (см фото);',
      user: {
        name: 'Константин Е.',
        country: 'Россия',
      },
      likes: 1,
      dislikes: 0,
      comments: [],
      rank: 24,
    },
    {
      id: '018eafb3-5daa-eb8e-f7da-2f2ec2b4f6a1',
      rating: 5,
      text: 'Хорошая клавиатура очень приятные кейкапы все работает по беспроводу и блютузу подсветка шикарная клавиатура бомба запокована хорошо сама упаковка чуть чуть помята',
      productArticle: 1300950270,
      positiveText: '',
      negativeText: '',
      user: {
        name: 'Пользователь предпочёл скрыть свои данные',
        country: 'Россия',
      },
      likes: 0,
      dislikes: 0,
      comments: [],
      rank: 25,
    },
    {
      id: '018eaaf9-afad-033d-b7b6-de3c1b42fc47',
      rating: 5,
      text: 'однозначно пять звезд, даже не знаю что можно еще добавить. самая лучшая клавиатура которая у меня была. для управления этим экранчиком, нужно нажать fn+нажать на колесико. для того чтобы гифку установить, обязательно скачайте именно ту версию по, у меня это ajazz ak820Pro(triple mode). вообщем всем советую к покупке, не пожалеете!!',
      productArticle: 1300950270,
      positiveText:
        'самая лучшая механическая клавиатура по соотношению цена-качество\nесть свой софт\nидеальнейший звук',
      negativeText: 'долгая доставка, однако ради этого потерпеть стоит',
      user: {
        name: 'Максим С.',
        country: 'Россия',
      },
      likes: 1,
      dislikes: 0,
      comments: [],
      rank: 26,
    },
    {
      id: '018eae0b-a501-d704-84ef-5e1b22bbb074',
      rating: 5,
      text: 'Клава классная, не пожалел что купил',
      productArticle: 1210357482,
      positiveText: '',
      negativeText: '',
      user: {
        name: 'Юрий Ш.',
        country: 'Россия',
      },
      likes: 0,
      dislikes: 0,
      comments: [],
      rank: 27,
    },
    {
      id: '018ead71-ded5-b478-1f5f-590249c360c4',
      rating: 5,
      text: 'Клава очень приятная, слегка шумная, но это можно будет исправить, за свои деньги топ',
      productArticle: 1210358865,
      positiveText: '',
      negativeText: '',
      user: {
        name: 'Матвей С.',
        country: 'Россия',
      },
      likes: 0,
      dislikes: 0,
      comments: [],
      rank: 28,
    },
    {
      id: '018eaa2e-d70d-d3f4-f07e-668076c7b2f5',
      rating: 5,
      text: 'Клавиатура хораша',
      productArticle: 1210358865,
      positiveText: '',
      negativeText: '',
      user: {
        name: 'Абдулгамид А.',
        country: 'Россия',
      },
      likes: 0,
      dislikes: 0,
      comments: [],
      rank: 29,
    },
    {
      id: '018ea8b5-459f-5f6d-bdb2-d7da0e76f9d5',
      rating: 5,
      text: 'Великолепно, но стоит привыкнуть',
      productArticle: 1300950270,
      positiveText: '',
      negativeText: '',
      user: {
        name: 'Пользователь предпочёл скрыть свои данные',
        country: 'Россия',
      },
      likes: 0,
      dislikes: 0,
      comments: [],
      rank: 30,
    },
    {
      id: '018ea7b5-ad46-dbae-2ab1-f6e5ea32f4dd',
      rating: 5,
      text: 'Очень классная клавиатура!!!',
      productArticle: 1300950270,
      positiveText: '',
      negativeText: '',
      user: {
        name: 'Марина С.',
        country: 'Россия',
      },
      likes: 0,
      dislikes: 0,
      comments: [],
      rank: 31,
    },
    {
      id: '018ea4c4-b3ba-bde5-4273-830010a43da4',
      rating: 5,
      text: 'Отличная клавиатура!!! Спасибо!',
      productArticle: 1210359103,
      positiveText: '',
      negativeText: '',
      user: {
        name: 'Алексей К.',
        country: 'Россия',
      },
      likes: 0,
      dislikes: 0,
      comments: [],
      rank: 32,
    },
    {
      id: '018ea4d7-8a2b-295b-cc14-4a42738d9bdf',
      rating: 5,
      text: 'Отличная клавиатура. Звук отличный, но чуточку громковат. Софт подключается и подсветка регулируется, также и клавиши. За свой прайс отлично, но хотелось бы сразу с русской раскладкой.',
      productArticle: 1210357482,
      positiveText: '',
      negativeText: '',
      user: {
        name: 'Илья Ф.',
        country: 'Россия',
      },
      likes: 0,
      dislikes: 0,
      comments: [
        {
          id: '018eaa27-9c6d-b23c-94c8-86a8b82a5e58',
          text: 'А где найти софт? Подскажите пожалуйста',
          user: {
            name: 'Абдулгамид А.',
            country: 'Россия',
          },
          likes: 0,
          dislikes: 0,
          rank: 1,
        },
      ],
      rank: 33,
    },
    {
      id: '018ea322-86a6-0dfa-eaeb-3392c45502f6',
      rating: 5,
      text: 'Хорошая клавиатура за свои деньги, свичи звучат приятно, кроме пробел – на мой слух слишком "басистый") А так все отлично, сразу поменяла кепки, но родные тоже приятные.',
      productArticle: 1210359103,
      positiveText: '',
      negativeText: '',
      user: {
        name: 'Полина У.',
        country: 'Россия',
      },
      likes: 0,
      dislikes: 0,
      comments: [],
      rank: 34,
    },
    {
      id: '018ea24a-4d78-c3e2-804a-8543ca5c163d',
      rating: 5,
      text: 'Всё работает',
      productArticle: 1210358981,
      positiveText: '',
      negativeText: '',
      user: {
        name: 'Надежда С.',
        country: 'Россия',
      },
      likes: 0,
      dislikes: 0,
      comments: [],
      rank: 35,
    },
    {
      id: '018ea447-c0ff-cd4e-103f-3e3c561ec760',
      rating: 5,
      text: 'клавиатура огонь\nминум вижу только один, и это то что нет кириллицы, но я могу писать вслепую',
      productArticle: 1210358865,
      positiveText: '',
      negativeText: '',
      user: {
        name: 'Илья Г.',
        country: 'Россия',
      },
      likes: 0,
      dislikes: 0,
      comments: [
        {
          id: '018ea535-1376-549f-f9dc-b29402c13559',
          text: 'Впрниципе не проблема, наклейки можно взять',
          user: {
            name: 'Арсений Л.',
            country: 'Россия',
          },
          likes: 0,
          dislikes: 0,
          rank: 1,
        },
      ],
      rank: 36,
    },
    {
      id: '018e9fbb-6a41-3121-e59a-ef573042f2fb',
      rating: 5,
      text: 'отличная клавиатура за эти деньги.\nИз минусов только что роллер люфтит, а еще подсветка только для декора, буквы не видно в темноте.',
      productArticle: 1210358865,
      positiveText: '',
      negativeText: '',
      user: {
        name: 'Владислав В.',
        country: 'Россия',
      },
      likes: 1,
      dislikes: 0,
      comments: [],
      rank: 37,
    },
    {
      id: '018e9f0f-b670-34ab-d2b1-92f6e0d3847c',
      rating: 5,
      text: 'Как для обычного обывателя, игравшего на нн оверпрайс механике, могу сказать, что по первом ощущениям это небо и земля по сравнению с тем, с чем я играл ранее. Супер мягкое нажатие, легкий вес, приятный глухой звук при тайпинге, да и сам внешний вид ого-го. Есть конечно свои минусы, в виде отсуствии кириллицы и не самого удобного софта, но это компенсирует все выше перечисленное. Не хочу пока говорить каких то громких заявлений, и бо не испытал ее в боевых условиях, но возможно, это одно из самых лучших приобретений среди клав в диапозоне 4-5к.',
      productArticle: 1300950270,
      positiveText: '',
      negativeText: '',
      user: {
        name: 'Кирилл А.',
        country: 'Россия',
      },
      likes: 0,
      dislikes: 0,
      comments: [],
      rank: 38,
    },
    {
      id: '018e8a6a-6170-3675-52b2-df1ad15afab9',
      rating: 4,
      text: 'клава рабочая, но пришла на блевотных, уродских синих свитчах, возможно я сам виноват, что не посмотрел на каких свитчах придет, но я не доволен(',
      productArticle: 1210358981,
      positiveText: '',
      negativeText: '',
      user: {
        name: 'Арсланбай В.',
        country: 'Россия',
      },
      likes: 0,
      dislikes: 3,
      comments: [
        {
          id: '018ea2ca-d1ec-0ad6-ba7b-fbfe5e631dc8',
          text: 'Виноват только ты',
          user: {
            name: 'Анатолий М.',
            country: 'Россия',
          },
          likes: 0,
          dislikes: 0,
          rank: 1,
        },
        {
          id: '018ead31-a34a-0e00-1b22-5c6d47853f28',
          text: 'Полностью согласен',
          user: {
            name: 'Максим Г.',
            country: 'Россия',
          },
          likes: 0,
          dislikes: 0,
          rank: 2,
        },
      ],
      rank: 39,
    },
    {
      id: '018e9b2b-096a-8f56-d1cc-728897908198',
      rating: 4,
      text: 'хорошая клавиатура, смазана с завода, только не понравились кейкапы',
      productArticle: 1210358865,
      positiveText: '',
      negativeText: '',
      user: {
        name: 'эшкерев А.',
        country: 'Россия',
      },
      likes: 0,
      dislikes: 0,
      comments: [],
      rank: 40,
    },
    {
      id: '018e8a9c-99c6-7704-13cb-1979d64b0c1f',
      rating: 5,
      text: 'Наверное, за 3 к хорошая клава, берите не пожалеете! ;)',
      productArticle: 1210357482,
      positiveText:
        'Это моя первая клавиатуры,поэтому немогу сказать хороша она или нет, но мне все нравится',
      negativeText:
        'Один минус, либо я привык к яркости, но у нее подсветка очень тусклая(по сравнению с моей мышкой", в темноте не видео букв,',
      user: {
        name: 'Айназ Х.',
        country: 'Россия',
      },
      likes: 0,
      dislikes: 0,
      comments: [],
      rank: 41,
    },
    {
      id: '018e9dad-ffa7-b6b9-b969-b0c18325a4ed',
      rating: 5,
      text: 'ну, я даже не знаю что сказать, клавиатура просто имба, свитчи, виды подсветки, переключение звуков колёсиком, хотсвап, качество кейкапов, всё на вышке',
      productArticle: 1210357482,
      positiveText: '',
      negativeText: '',
      user: {
        name: 'Оксана П.',
        country: 'Россия',
      },
      likes: 0,
      dislikes: 0,
      comments: [
        {
          id: '018eacee-6e1d-fc8e-5f5a-4b1b54f40c00',
          text: '"Переключение звуков" имеется в виду переключение треков вперёд/назад?',
          user: {
            name: 'Никита М.',
            country: 'Россия',
          },
          likes: 0,
          dislikes: 0,
          rank: 1,
        },
      ],
      rank: 42,
    },
  ]

  // if (!data || data.status === 'error') {
  //   return {
  //     feedbacks: [],
  //     feedbacksCount: 0,
  //   }
  // }

  data.forEach((feedback: any) => {
    feedback.comments.forEach((comment: any) => {
      comment.addLikes = 0
      comment.addDislikes = 0
    })
  })

  return {
    feedbacks: data,
    feedbacksCount: 0,
  }
})
